export const products = [
    {
        "id": 0,
        "name": 'Sữa rửa mặt Trà Xanh Innisfree',
        "idCategory": 1, 
        "image": 'Images/allProducts/01.png',
        "image1": 'Images/allProducts/011.png',
        "image2": 'Images/allProducts/012.png',
        "image3": 'Images/allProducts/013.png',
        "price": 180000, 
        "descripton": 'Sữa rửa mặt chiết xuất trà xanh Innisfree với tính chất dịu nhẹ được chiết xuất hoàn toàn từ lá trà xanh tự nhiên. Sự tinh khiết của lá trà xanh được tinh chế bằng cách chưng cất tinh lá trà của đảo Jeju tạo nên sức dưỡng ẩm sâu cho sữa rửa mặt. Giàu độ ẩm và các thành phần chống oxi hoá và kaolin giúp làm sạch bụi bẩn và các tạp chất trên da, hút nhờn và ngăn ngừa các dấu hiệu lão hóa.',
        "oldPrice": 220000, 
        "vote": 5,
        "brand": 'Innisfree',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 1,
        "name": 'Sữa rửa mặt đá tro núi lửa Innisfree',
        "idCategory": 1, 
        "image": 'Images/allProducts/11.png',
        "image1": 'Images/allProducts/111.png',
        "image2": 'Images/allProducts/112.png',
        "image3": 'Images/allProducts/113.png',
        "price": 260000, 
        "descripton": 'Sữa Rửa Mặt Tro Núi Lửa Trị Mụn Đầu Đen, Bã Nhờn Innisfree Jeju Volcanic Pore Cleansing Foam Ex là sữa rửa mặt thuộc thương hiệu Innisfree với chiết xuất Tro Núi Lửa hút mụn đầu đen, mụn cám, bã nhờn. Sữa rửa mặt làm sạch da, giảm mụn, se khít lỗ chân lông.',
        "oldPrice": 300000, 
        "vote": 5, 
        "brand": 'Innisfree',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 2,
        "name": 'Serum Evolve Organic Beauty ',
        "idCategory": 2, 
        "image": 'Images/allProducts/22.png',
        "image1": 'Images/allProducts/221.png',
        "image2": 'Images/allProducts/222.png',
        "image3": 'Images/allProducts/223.png',
        "price": 420000, 
        "descripton": 'Chứa Axit hyaluronic giúp giảm nếp nhăn, làm cho làn da tươi trẻ và cải thiện làn da cùng chiết xuất quả lựu giàu axit ellagic, giúp điều chỉnh quá trình đổi mới tế bào và củng cố màng tế bào. Do đó, sự mất độ ẩm và thiệt hại do các gốc tự do gây ra sẽ được ngăn chặn  chất hạnh nhân và cà chua, chiết xuất Vitamin C & E, dưa chuột, lô hội, giúp bề mặt da luôn được dưỡng ẩm khi tiếp xúc ánh măt trời',
        "oldPrice": 450000,
        "vote": 5, 
        "brand": 'Nature Gate',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 3,
        "name": 'Serum Ordinary Niacinamide',
        "idCategory": 2,
        "image": 'Images/allProducts/32.png',
        "image1": 'Images/allProducts/321.png',
        "image2": 'Images/allProducts/322.png',
        "image3": 'Images/allProducts/323.png',
        "price": 320000, 
        "descripton": 'Chứa Niacinamide giúp CẢI THIỆN SẮC TỐ DA, giúp giảm vết thâm, làm sáng và trắng da, từ nồng độ 5% trở lên, Niacinamide mang lại tác dụng làm trắng ra rất nhanh, đặc biệt với làn da châu Á. Niacinamdide còn giúp GIẢI QUYẾT VẤN ĐỀ DẦU VÀ MỤN, Ở nồng độ 5% trở lên, Niacinamide có khả năng kháng viêm, nó giúp giảm viêm da do tế bào chết gây ra, ngoài ra còn giúp kiểm soát nhờn và giảm dầu thừa hiệu quả. ',
        "oldPrice": 350000,
        "vote": 5, 
        "brand": 'Evolve Organic Beauty',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 4,
        "name": 'Serum Klairs Freshly Juiced Drop ',
        "idCategory": 2, 
        "image": 'Images/allProducts/41.png',
        "image1": 'Images/allProducts/411.png',
        "image2": 'Images/allProducts/412.png',
        "image3": 'Images/allProducts/413.png',
        "price": 300000, 
        "descripton": '"Thâm mụn" luôn là vấn đề phiền toái khiến làn da chúng ta trở nên kém xinh, mất thẩm mỹ trong mắt người nhìn. Để làn da trở nên đều màu, mờ thâm thì chắc hẳn không thể bỏ qua Vitamin C - một trong những ứng cử viên sáng giá cải thiện làn da thâm mụn. Tinh Chất Làm Sáng Da Serum Klairs Freshly Juiced Drop chiết xuất từ vitamin C tinh khiết giúp phục hồi, làm sáng màu và trẻ hóa làn da mà không hề lo kích ứng da, kể cả da nhạy cảm.',
        "oldPrice": 340000,
        "vote": 3, 
        "brand": 'Innisfree',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 5,
        "name": 'Serum Melano CC Whitening Essence',
        "idCategory": 2, 
        "image": 'Images/allProducts/51.png',
        "image1": 'Images/allProducts/511.png',
        "image2": 'Images/allProducts/512.png',
        "image3": 'Images/allProducts/513.png',
        "price": 450000, 
        "descripton": 'Tinh Chất Làm Sáng Da, Mờ Thâm Nám Melano CC Whitening Essence là tinh chất dưỡng da thuộc thương hiệu Melano CC sự kết hợp giữa Vitamin C tinh khiết và Vitamin E, thấm sâu vào lớp đáy da ngăn ngừa sự hình thành và làm mờ hắc tố melanin (tác nhân gây ra vết thâm nám, tàn nhang), từng bước làm da trắng sáng từ bên trong. Là 1 trong những sản phẩm bán chạy nhất của thương hiệu Melano CC (Nhật Bản).',
        "oldPrice": 480000, 
        "vote": 5,
        "brand": 'Innisfree',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 6,
        "name": 'Son dưỡng Yves Rocher Cerise',
        "idCategory": 3,
        "image": 'Images/allProducts/63.png',
        "image1": 'Images/allProducts/631.png',
        "image2": 'Images/allProducts/632.png',
        "image3": 'Images/allProducts/633.png',
        "price": 100000,
        "descripton": 'Mùi hương ngọt ngào & nóng bỏng của quả Anh đào khiến đôi môi của bạn mềm mại hơn & được thể hiện bằng một ánh sáng màu đỏ bóng loáng.',
        "oldPrice": '150000đ',
        "vote": 2,
        "brand": 'Yves Rocher',
        "categoryName": 'Chăm sóc môi'
    },

    {
        "id": 7,
        "name": 'Son dưỡng Yves Rocher Vanille',
        "idCategory": 3,
        "image": 'Images/allProducts/73.png',
        "image1": 'Images/allProducts/731.png',
        "image2": 'Images/allProducts/732.png',
        "image3": 'Images/allProducts/733.png',
        "price": 100000,
        "descripton": 'Son chứa chiết xuất va ni - Vanilla chứa nhiều chất chống oxy hoá cao, giúp bảo vệ da khỏi những tác động xấu và mùi hương dịu nhẹ, thư giãn, giảm stress ngay tức thì',
        "oldPrice": '150000đ',
        "vote": 5,
        "brand": 'Yves Rocher',
        "categoryName": 'Chăm sóc môi'
    },

    {
        "id": 8,
        "name": 'Son dưỡng Yves Rocher Karité',
        "idCategory": 3,
        "image": 'Images/allProducts/83.png',
        "image1": 'Images/allProducts/831.png',
        "image2": 'Images/allProducts/832.png',
        "image3": 'Images/allProducts/833.png',
        "price": 100000,
        "descripton": 'Chất kem nhẹ được nhuộm trong một tông màu berry tinh tế và do đó nhấn mạnh hình dạng tự nhiên của đôi môi của bạn.',
        "oldPrice": '150000đ',
        "vote": 5,
        "brand": 'Yves Rocher',
        "categoryName": 'Chăm sóc môi'
    },
    {
        "id": 9,
        "name": 'Kem chống nắng Sunprise Mild Watery',
        "idCategory": 0, 
        "image": 'Images/allProducts/90.png',
        "image1": 'Images/allProducts/901.png',
        "image2": 'Images/allProducts/902.png',
        "image3": 'Images/allProducts/903.png',
        "price": 250000, 
        "descripton": 'Được kết hợp từ nước khoáng cùng với các dưỡng chất thiết yếu khác như Diethylamino Hydroxybenzoyl Hexyl Benzoate, Alcohol, Butylene Glycol, Dicaprylyl Carbonate và các chiết xuất từ cam, chanh, hoa hướng dương cùng đậu nành, đây là dòng kem chống nắng Mỏng Nhẹ, an toàn với da nhạy cảm',
        "oldPrice": 280000, 
        "vote": 5, 
        "brand": 'Etude house',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 10,
        "name": 'Kem chống nắng Sunprise Must Daily',
        "idCategory": 0, 
        "image": 'Images/allProducts/100.png',
        "image1": 'Images/allProducts/1001.png',
        "image2": 'Images/allProducts/1002.png',
        "image3": 'Images/allProducts/1003.png',
        "price": 280000, 
        "descripton": 'chiết xuất từ quả Acai, Arcerola, nha đam, hoa cây đoạn, cây cói túi, Vitamin D, mùi thơm nhẹ, không gây nhờn rít và không kích ứng da',
        "oldPrice": 300000,
        "vote": 5, 
        "brand": 'Etude house',
        "categoryName": 'Chăm sóc da'
    },
    {
        "id": 11,
        "name": 'Kem chống nắng Nature’s Gate',
        "idCategory": 0,
        "image": 'Images/allProducts/110.png',
        "image1": 'Images/allProducts/1101.png',
        "image2": 'Images/allProducts/1102.png',
        "image3": 'Images/allProducts/1103.png',
        "price": 300000,
        "descripton": 'Tinh chất hạnh nhân và cà chua, chiết xuất Vitamin C & E, dưa chuột, lô hội, giúp bề mặt da luôn được dưỡng ẩm khi tiếp xúc ánh măt trời',
        "oldPrice": 350000, 
        "vote": 3, 
        "brand": 'Nature Gate',
        "categoryName": 'Chăm sóc da'
    }
]